### PR TITLE
Analyze with presto

### PR DESCRIPTION
**Pull request by findepi**

### CODE REVIEW

**Comment by mosabua** [comment]
@bitsondatadev maybe you could work with @findepi to update this post and rejig it to be a follow up to your post a week or two after?

**Comment by bitsondatadev** [comment]
> @bitsondatadev maybe you could work with @findepi to update this post and rejig it to be a follow up to your post a week or two after?

By rejig are you talking about embedding a katacoda example here as well?

**Comment by findepi** [comment]
That version is not relevant, and i did not find time to produce a better version yet. Volunteers?

**Comment by mosabua** [comment]
I think @bitsondatadev and @findepi can work together on this to get it improved .. and publish as a follow up to the PR Brian is work on now.

**Comment by mosabua** [comment]
And we can also take some of that content and see if it would fit in the docs

**Comment by bitsondatadev** [comment]
Sounds good to me! I'll look at this a little over the weekend.

**Pull request closed without merging**
