### PR TITLE
Content edits for style and readability

### PR DESCRIPTION
**Pull request by mosabua**
- grammar and spelling fixes
- comma additions
- avoiding future tense

Signed-off-by: Manfred Moser <mmoser@apache.org>
Signed-off-by: Manfred Moser <manfred@simpligility.com>

### CODE REVIEW

**Comment by mosabua** [comment]
@electrum @martint @dain @findepi .. feel free to have a look and merge away.

**Comment by martint** [comment]
Looks good. Can you rebase on latest master? There are some conflicts due to changes in `resources.md`

**Comment by mosabua** [comment]
So weird .. I rebased now and it still show conflicts. Let me know if you need me to merge it somehow or help with resolving.

**Comment by martint** [comment]
I think it's because of that merge commit you have at the end. Let me see if I can fix it.

**Comment by martint** [comment]
Merged, thanks!

**Pull request closed without merging**
