### PR TITLE
Add the presto community broadcast show note pages

### PR DESCRIPTION
**Pull request by bitsondatadev**
These episode pages work similar to the blog pages but are on a distinct rss feed and page. They are linked from Community > Presto Community Broadcast > Show Notes. 

TODO  before we commit.
 ~1) invert list order to most recent on top.~

### CODE REVIEW

**Comment by mosabua** [comment]
I think we should have a dedicated back about PCB where we link from instead of just the little link to show notes.

Just a simple page with info like

* when
* who
* topics
* links to twitch, youtube, ... whatever else

**Comment by bitsondatadev** [comment]
> I think we should have a dedicated back about PCB where we link from instead of just the little link to show notes.

When you said _back_ should be page in what you said above? Correct me if i'm wrong.

I agree this would be useful. My initial thoughts are to put it above the episodes, and then have a few of the most recent episodes below. We could also have a main PCB page that links to all you mention (also can have a "where to listen" link to our Apple, Google, Spotify, etc...). Then one of the links takes you to the list of episode show notes.

**Comment by bitsondatadev** [comment]
Updated this @mosabua... I moved the episode list to /broadcast/episodes.md and now broadcast/index.md is the home for overview of info on PCB.

**Review by mosabua — APPROVED** [review]
I reviewed and edited this with Brian together. Mostly the index page and the general layout and setup for the individual episodes. I think this is good to go.

**Comment by bitsondatadev** [comment]
Cleared out a few links in the show notes that linked to the Starburst newsletter and the extra link to the starburst homepage.

**Pull request merged**
