### PR TITLE
Fix paper page when used with trailing slash

### PR DESCRIPTION
**Pull request by electrum**

### CODE REVIEW

**Comment by mosabua** [comment]
Why would the page have a trailing / in the URL?

**Comment by electrum** [comment]
The URL can be accessed in several ways

* https://prestosql.io/paper.html
* https://prestosql.io/paper
* https://prestosql.io/paper/

 People often type URLs manually and thus it might end in a trailing slash. If we're going to serve the page, it shouldn't be broken. (and we don't have a choice on serving it or redirecting since that's what Netlify does)

**Comment by electrum** [comment]
Note that the entire Jekyll site is generated to be in the root context. I don't see a problem with that, since the site has a singular purpose. This is different from the documentation, which is intentionally generated to be relative, as it might be used in different contexts.

**Comment by mosabua** [comment]
I would use ./ as a fix then ..

**Pull request merged**
