### PR TITLE
Exclude file configuration

### PR DESCRIPTION
**Pull request by mosabua**
- added readme
- added config to avoid internal files become part of hosted site

Signed-off-by: Manfred Moser <mmoser@apache.org>
Signed-off-by: Manfred Moser <manfred@simpligility.com>

### CODE REVIEW

**Comment by mosabua** [comment]
@electrum @martint @dain @findepi .. feel free to have a look and merge away.

Last one for today ;-)

**Comment by martint** [comment]
By the way, we don't use `Signed-off-by:` for Presto. We use author/committer to track who made a change.

**Comment by mosabua** [comment]
Sounds good. We should chat about PR merge process and such tomorrow anyway ...

**Comment by martint** [comment]
Merged, thanks!

**Pull request closed without merging**
